name: News Scrapper

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 10 minutes
  workflow_dispatch:

# Grant write permissions to the GITHUB_TOKEN
permissions:
  contents: write  # Allow pushing changes

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use the token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run:  |
          python NewsExtract.py
        

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update data" || echo "No changes to commit"
          # Use the GITHUB_TOKEN for authentication
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git