name: Upload latest_news.json to Firebase Storage

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch (adjust as needed)

jobs:
  upload-to-firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Get Firebase Private Key
      id: firebase-private-key
      run: echo "::set-output name=privateKey::${{ secrets.FIREBASE_PRIVATE_KEY }}"

    - name: Get Firebase Credentials
      id: firebase-credentials
      run: echo "::set-output name=credentials::${{ secrets.FIREBASE_CREDENTIALS }}"

    - name: Authenticate Firebase
      run: |
        combinedCredentials=$(echo "${{ steps.firebase-credentials.outputs.credentials }}" | jq -r '. + {privateKey: "'${{ steps.firebase-private-key.outputs.privateKey }}'" }')
        echo "$combinedCredentials" > firebase_creds.json
        firebase use --add
        firebase login:ci --no-localhost "$combinedCredentials"


    - name: Upload latest_news.json
      run: |
        firebase deploy --only storage --token "$(firebase login:ci --no-localhost "$combinedCredentials")" --project ${{ secrets.FIREBASE_CREDENTIALS | jq -r '.project_id' }}

