name: News Scrapper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

permissions:
  contents: write  # Allow pushing changes

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use the token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run News Scraper
        run: python NewsExtract.py

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-credentials.json

      - name: Upload JSON to Firebase
        run: |
          firebase database:set /news ./latest_news.json --project ai-news-d465d
