name: Update Firebase Storage

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch (adjust as needed)

jobs:
  upload-to-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Get Firebase Private Key
        id: firebase-private-key
        run: echo "::set-output name=privateKey::${{ secrets.FIREBASE_PRIVATE_KEY }}"

      - name: Get Firebase Credentials
        id: firebase-credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > firebase_creds.json

      - name: Extract Firebase Project ID
        id: project-id
        run: echo "PROJECT_ID=$(jq -r '.project_id' firebase_creds.json)" >> $GITHUB_ENV

      - name: Authenticate Firebase
        run: |
          firebase use --add --token "$(cat firebase_creds.json)"
          firebase login:ci --no-localhost "$(cat firebase_creds.json)"

      - name: Upload latest_news.json
        run: firebase deploy --only storage --token "$(cat firebase_creds.json)" --project $PROJECT_ID
