name: Upload News JSON  # Changed name to reflect its purpose

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allow pushing changes

jobs:
  upload-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-credentials.json

      - name: Upload JSON to Firebase
        run: |
          firebase database:set /news ./latest_news.json --project ai-news-d465d --confirm
